"""Add Cita model

Revision ID: 239492d1183e
Revises: cafc287e5620
Create Date: 2026-06-05 16:13:46.871588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239492d1183e'
down_revision: Union[str, Sequence[str], None] = 'cafc287e5620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cita',
    sa.Column('id_cita', sa.UUID(), nullable=False),
    sa.Column('id_incidente_origen', sa.UUID(), nullable=True),
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.Column('id_vehiculo', sa.UUID(), nullable=False),
    sa.Column('id_taller', sa.UUID(), nullable=False),
    sa.Column('id_sucursal', sa.UUID(), nullable=False),
    sa.Column('id_tecnico', sa.UUID(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('rol_creador', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_incidente_origen'], ['incidente.id_incidente'], ),
    sa.ForeignKeyConstraint(['id_sucursal', 'id_taller'], ['sucursal_taller.id_sucursal', 'sucursal_taller.id_taller'], name='fk_cita_sucursal'),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ),
    sa.ForeignKeyConstraint(['id_tecnico'], ['tecnico.id_tecnico'], ),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculo.id_vehiculo'], ),
    sa.PrimaryKeyConstraint('id_cita')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cita')
    # ### end Alembic commands ###
