"""add fcm_token to user

Revision ID: a754325fd0a6
Revises: 65065b8dc1c5
Create Date: 2026-04-27 03:07:01.311364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a754325fd0a6'
down_revision: Union[str, Sequence[str], None] = '65065b8dc1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('fcm_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'fcm_token')
    # ### end Alembic commands ###
