"""add_technician_verification

Revision ID: cafc287e5620
Revises: 6f00fc9d2680
Create Date: 2026-06-04 21:07:27.957440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cafc287e5620'
down_revision: Union[str, Sequence[str], None] = '6f00fc9d2680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verificacion_tecnico',
    sa.Column('id_verificacion', sa.UUID(), nullable=False),
    sa.Column('id_incidente', sa.UUID(), nullable=False),
    sa.Column('id_asignacion', sa.UUID(), nullable=True),
    sa.Column('id_tecnico', sa.UUID(), nullable=False),
    sa.Column('metodo_verificacion', sa.String(length=50), nullable=False),
    sa.Column('codigo_verificacion', sa.String(length=10), nullable=False),
    sa.Column('estado_verificacion', sa.String(length=50), nullable=False),
    sa.Column('fecha_verificacion', sa.DateTime(), nullable=True),
    sa.Column('resultado', sa.String(length=50), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('usuario_validador', sa.String(length=150), nullable=True),
    sa.Column('motivo_override', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_asignacion'], ['asignacion_incidente.id_asignacion'], ),
    sa.ForeignKeyConstraint(['id_incidente'], ['incidente.id_incidente'], ),
    sa.ForeignKeyConstraint(['id_tecnico'], ['tecnico.id_tecnico'], ),
    sa.PrimaryKeyConstraint('id_verificacion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verificacion_tecnico')
    # ### end Alembic commands ###
